### ISSUE TITLE
extraction-plugin: support for appDir in NextJS 13

### ISSUE THREAD

**Issue by Dwlad90** [microsoft/griffel#266] opened 2022-10-27 19:43 UTC
Hi,
I was trying to use  NextJS v13 appDir mode with `@griffel` and I get the following errors:

```bash
Attempted import error: '__css' is not exported from '@griffel/react' (imported as '__css').
```

and

```bash
TypeError: core.createDOMRenderer is not a function
    at 4415 (/home/projects/nextjs-ltekvi/.next/server/chunks/792.js:3446:88)
    at __webpack_require__ (/home/projects/nextjs-ltekvi/.next/server/webpack-runtime.js:25:43)
    at 5933 (/home/projects/nextjs-ltekvi/.next/server/chunks/792.js:3829:23)
    at __webpack_require__ (/home/projects/nextjs-ltekvi/.next/server/webpack-runtime.js:25:43)
    at 9692 (/home/projects/nextjs-ltekvi/.next/server/chunks/792.js:3710:18)
    at __webpack_require__ (/home/projects/nextjs-ltekvi/.next/server/webpack-runtime.js:25:43)
    at 4312 (/home/projects/nextjs-ltekvi/.next/server/app/page.js:99:72)
    at __webpack_require__ (/home/projects/nextjs-ltekvi/.next/server/webpack-runtime.js:25:43)
    at eval (/home/projects/nextjs-ltekvi/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:918:337)
```

There are errors only when using the '@griffel/next-extraction-plugin' package. 

To reproduce these errors g to the [Sandbox](https://stackblitz.com/edit/nextjs-ltekvi) and run the command:
```bash 
npm install && npx next build
```

**Comment by layershifter** [comment] 2022-10-31 10:25
Hey, looks pretty strange TBH as `__css` is exported:

![image](https://user-images.githubusercontent.com/14183168/198986817-a03d9cd1-c768-4158-b9a6-195b5e252f70.png)

I will look into it in upcoming weeks.

**Comment by Dwlad90** [comment] 2022-11-01 10:13
> Hey, looks pretty strange TBH as `__css` is exported:
> 
> ![image](https://user-images.githubusercontent.com/14183168/198986817-a03d9cd1-c768-4158-b9a6-195b5e252f70.png)
> 
> I will look into it in upcoming weeks.

@layershifter,
Yes, I checked, these lines are present in the built code, as well as the createDOMRenderer export. This is a very strange bug.

Thank you!

**Comment by iammathew** [comment] 2022-11-02 13:50
Linking this discussion here, since I think it may be related 🤔 https://github.com/microsoft/fluentui/discussions/25384
I may be mistaken though

**Comment by layershifter** [comment] 2022-11-23 12:47
> Linking this discussion here, since I think it may be related 🤔 [microsoft/fluentui#25384](https://github.com/microsoft/fluentui/discussions/25384)
> I may be mistaken though

No, it's not related to that. This issue is purely related to [CSS extraction](https://griffel.js.org/react/css-extraction/introduction).

**Comment by Dwlad90** [comment] 2022-11-24 19:44
> @Dwlad90 it seems that I traced the problem, looks that it's happening in webpack loader from `webpack-extraction-plugin`.
> 
> Looks like Next.js (or its Webpack part) does not like how we emit imports there:
> 
> https://github.com/microsoft/griffel/blob/ebd004e9e8935e099c1873bf2d4841c773bb8417/packages/webpack-extraction-plugin/src/webpackLoader.ts#L107-L114
> 
> If **imports for CSS** are not there - then it _works_ 😳 I did following change and then build is passing:
> 
> ```diff
>             const request = `import ${JSON.stringify(this.utils.contextify(this.context || this.rootContext, `griffel.css!=!${virtualLoaderPath}!${resourcePath}?style=${toURIComponent(result.cssRules.join('\n'))}`))};`;
> -            this.callback(null, `${result.code}\n\n${request};`, result.sourceMap);
> +            this.callback(null, `${result.code}`, result.sourceMap);
>             return;
> ```
> 
> ![image](https://user-images.githubusercontent.com/14183168/203550066-17f660de-3fd2-49ce-aaab-a215c885498b.png)
> 
> I will look more to understand why it happens and how to fix it later this/next week.

Thanks for the answer! Good to know.
I'll be waiting for the fix.

**Comment by layershifter** [comment] 2022-12-07 13:23
<img width="200" alt="image" src="https://user-images.githubusercontent.com/14183168/206185415-1601636b-3aa2-401c-9edf-9a31ec2e0abd.png">

\* my face when I found the reason *

----

- we run a loader that creates CSS imports only for files that contain `__styles`/`__resetStyles`
  https://github.com/microsoft/griffel/blob/735cbfdc1e1ca7f12928393acdb98e295ed6133e/packages/webpack-extraction-plugin/src/webpackLoader.ts#L46-L47
- (we don't analyze AST at that point as invoking Babel is **significantly** more expensive than just `.indexOf`)
- (it means that a string that contains "__styles" is enough to invoke Babel processing)
- once a Babel plugin will process file - we have a nice condition to emit imports that will trigger `css-loader`
  https://github.com/microsoft/griffel/blob/735cbfdc1e1ca7f12928393acdb98e295ed6133e/packages/webpack-extraction-plugin/src/webpackLoader.ts#L68
- it **does not work** both in current and older versions as `.cssRules`/`.cssRulesByBucket` will always empty array/empty object 💥 
  <img width="486" alt="image" src="https://user-images.githubusercontent.com/14183168/206189718-43c40445-03fa-4b43-b618-53fd10c243f8.png">
- as a result plugin emit invalid imports and everything goes wild 🔥 

---

@Dwlad90 For older version you just need a following patch in `node_modules/@griffel/webpack-extraction-plugin/src/webpackLoader.js`:

```diff
if (result) {
-       if (result.cssRules) {
+       if (result.cssRules.length > 0) {
```

For newer, I have a fix already in #289.

**Comment by layershifter** [comment] 2022-12-09 11:40
#289 fixed the problem, but #291 added an another one. For unknown reason React wants to execute our import:

![image](https://user-images.githubusercontent.com/14183168/206694634-44183c84-b6a7-4166-b2ee-ff9b95898e0d.png)

**Comment by layershifter** [comment] 2022-12-09 11:48
Build is passing if it will not be execute for server i.e. the whole condition will be wrapped into `!isServer`:

https://github.com/microsoft/griffel/blob/d144cdef12e57d575732a19a51daa4da7ede3707/packages/next-extraction-plugin/src/lib/next-extraction-plugin.ts#L71-L79

The problem is that then CSS does not load while it's generated:
![image](https://user-images.githubusercontent.com/14183168/206695961-f8e5b53a-fb78-4a46-8307-c3274a8d23e6.png)

Need to check what happens there. Will look into it next week.

**Comment by Dwlad90** [comment] 2022-12-11 00:18
@layershifter, Thanks for the solution of the problem.

But I noticed that when I add the condition to process styles on the client assembly only, then Webpack successfully compiled and extract the styles. However on the page the CSS file wasn't loaded and, accordingly, there are no styles on the page.

To reproduce these errors go to the [Sandbox](https://stackblitz.com/edit/nextjs-jomtfx) and run the command:

```zsh
npm install && npx next build && npm next start
```

***


Also I found another issue, when using the RendererProvider in the `./app/layout.tsx` I get the following error:

```zsh
info  - Collecting page data .TypeError: React__namespace.createContext is not a function
    at 4947 (file:///home/projects/nextjs-ikosio/.next/server/chunks/854.js:6871:60)
    at __webpack_require__ (file:///home/projects/nextjs-ikosio/.next/server/webpack-runtime.js:25:43)
    at 2562 (file:///home/projects/nextjs-ikosio/.next/server/chunks/854.js:7197:23)
    at __webpack_require__ (file:///home/projects/nextjs-ikosio/.next/server/webpack-runtime.js:25:43)
    at 3294 (file:///home/projects/nextjs-ikosio/.next/server/chunks/854.js:7089:18)
    at __webpack_require__ (file:///home/projects/nextjs-ikosio/.next/server/webpack-runtime.js:25:43)
    at 8748 (file:///home/projects/nextjs-ikosio/.next/server/app/page.js:140:72)
    at Function.__webpack_require__ (file:///home/projects/nextjs-ikosio/.next/server/webpack-runtime.js:25:43)
    at async collectGenerateParams (file:///home/projects/nextjs-ikosio/node_modules/next/dist/build/utils.js:713:17)
    at async eval (file:///home/projects/nextjs-ikosio/node_modules/next/dist/build/utils.js:853:36)
```

To reproduce these errors go to the [Sandbox](https://stackblitz.com/edit/nextjs-ikosio) and run following command:

```zsh
npm install && npx next build
```


Maybe it happens because of the limitations of the Server Components, currently the use of CSS-in-JS
 is not supported, [proof](https://beta.nextjs.org/docs/styling/css-in-js).

If you uncomment the line

```tsx
'use client'
```

 in the `./app/layout.tsx` file, so turn the component into Client Component, then the error disappears.

**Comment by layershifter** [comment] 2022-12-12 09:13
> But I noticed that when I add the condition to process styles on the client assembly only, then Webpack successfully compiled and extract the styles. However on the page the CSS file wasn't loaded and, accordingly, there are no styles on the page.

Yeah, it's the same problem that I faced. Will look into it more.

> Also I found another issue, when using the RendererProvider in the ./app/layout.tsx I get the following error:

Out of curiosity, why do you need it with CSS extraction? It's not used when CSS extraction is in place.

> in the ./app/layout.tsx file, so turn the component into Client Component, then the error disappears.

It's a thing that I don't really like. Components that use `useState` or `useContext` can be only Client Components, but `makeStyles` (`__styles` & `__css`) consuming a context for `TextDirection`...

**Comment by taishinaritomi** [comment] 2023-01-05 08:52
#303

I cloned the code and checked it out a bit, but I have never used nx, etc. and it seemed to take me a while to understand it, so I will share about the next-extraction-plugin here.


---

The first thing I did was to tell getGlobalCssLoader that it is app-dir.
This way the client component should be able to extract the CSS.

https://github.com/microsoft/griffel/blob/16250ce781f4f8329270ad83fdead9922bdfc234/packages/next-extraction-plugin/src/lib/next-extraction-plugin.ts#L81-L96

```ts
const isAppDir = nextConfig.experimental?.appDir === true;
const appDirOptions = isAppDir
  ? {
      hasAppDir: true,
      experimental: { appDir: true },
    }
  : {};

  cssRules.unshift({
    test: /griffel\.css$/i,
    sideEffects: true,
    use: getGlobalCssLoader(
      {
        assetPrefix: config.assetPrefix,
        isClient: !isServer,
        isServer,
        isDevelopment: dev,
        future: nextConfig.future || {},
        experimental: nextConfig.experimental || {},
        ...appDirOptions,
      } as ConfigurationContext,
      () => lazyPostCSS(dir, getSupportedBrowsers(dir, dev), undefined),
      [],
    ),
  });
```


For the react server components, since hooks are not available You will need to rethink your design in order to get it to work.
If griffel can be designed without using hooks, the css for "nextjs13 react server components" cannot be extracted by the virtualLoader, so it can be written out to a file once and it will work.([example](https://github.com/taishinaritomi/kaze-style/blob/13cf55937048c362ed92d6e1b6fe416c202d1e24/packages/webpack-plugin/src/loader.ts#L77-L88
))

**Comment by Dwlad90** [comment] 2023-02-20 07:25
Hi @layershifter,
Maybe it will be helpful,
a new [webpack plugin](https://github.com/SukkaW/style9-webpack) of [style9](https://github.com/johanholmerin/style9) now supports this feature.
This is a [link](https://github.com/johanholmerin/style9/pull/83) to a discussion about NextJS appDir and CSS-in-JS support.
Can you check if this is relevant to @griffel?

**Comment by layershifter** [comment] 2023-02-22 13:29
@Dwlad90 yes, this looks relevant and explains what current thing does work. I will look into it in upcoming weeks, but feel free to do the same if you are interested 😉

**Comment by SukkaW** [comment] 2023-02-24 18:41
> @Dwlad90 yes, this looks relevant and explains what current thing does work. I will look into it in upcoming weeks, but feel free to do the same if you are interested 😉

FYI, I have described the Next.js issue here: https://github.com/SukkaW/style9-webpack/issues/1#issuecomment-1406730266, and I quote:

> https://github.com/vercel/next.js/blob/3a9bfe60d228fc2fd8fe65b76d49a0d21df4ecc7/packages/next/src/build/webpack/plugins/flight-client-entry-plugin.ts#L425-L429
> ```ts
> const modRequest: string | undefined =
>   mod.resourceResolveData?.path + mod.resourceResolveData?.query
> ```
> Here, only path and query are passed down, and all loaders are ignored.

-----

And you can find my workaround here: https://github.com/SukkaW/style9-webpack/compare/f468bf88782c8f578e45ae9dd9291e90bc45f97f...696f4e0645cbe1865de3249e5588a55e7d8c9775

In short, you can't use resource match query (`!=!`) and inline loader (`!virtual-file-loader.js?{}!`), as they will be dropped by Next.js Server Component CSS Extraction. You should pass the virtual CSS information directly to the `noop.css` (The actual file existing on the disk, required by the webpack) like this:

```js
import 'noop.css?{ filename, source }'
```

Then you will need to create a loader to extract `{ filename, source }` from the `noop.css` request.

**Comment by layershifter** [comment] 2023-08-28 14:21
@Dwlad90 can you please re-test with the latest Next.js? I was able to compile your example without any issues:

<img width="1122" alt="image" src="https://github.com/microsoft/griffel/assets/14183168/256cf219-ccb4-4300-b705-c11c719afce4">

**Comment by Dwlad90** [comment] 2023-08-30 20:16
@layershifter, Thank you.
I confirm, sandbox of [the comment](https://github.com/microsoft/griffel/issues/266#issue-1426182514) have been compiled successful with latest versions of `next` and `@griffel/*` packages when I added `'use client'` to `layout.tsx`.

**Comment by layershifter** [comment] 2023-08-31 07:36
@Dwlad90 thanks for confirmation, closing.

**Closed by layershifter** 2023-08-31 07:36 UTC
Labels: 🐞 bug
