### ISSUE TITLE
Build time transforms cannot use shorthands

### ISSUE THREAD

**Issue by taishinaritomi** [microsoft/griffel#167] opened 2022-07-19 09:56 UTC
Thanks for making a very good library.

I tried using "@griffel/webpack-extraction-plugin" in "Nextjs".
almost everything works perfectly, but "makeStyles" using "shorthands" is not bundled in css

**Comment by layershifter** [comment] 2022-07-19 10:11
Hey, can you please create a repro on https://stackblitz.com/ or https://codesandbox.io/? So we can check in which conditions and which styles are broken.

**Comment by taishinaritomi** [comment] 2022-07-19 14:07
I made a sample with codesandbox
Please check.

https://codesandbox.io/s/cranky-black-h2ofbr

**Comment by layershifter** [comment] 2022-07-22 08:31
Closing as a duplicate of #154. We will get to it and fix it.

**Closed by layershifter** 2022-07-22 08:31 UTC
